services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=full
      - KRAKEN_API_KEY=${KRAKEN_API_KEY}
      - KRAKEN_API_SECRET=${KRAKEN_API_SECRET}
      - MONGO_URL=${MONGO_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          cpus: '0.25'